#SPDX-License-Identifier: MIT-0
---
# tasks file for bouchta
- import_tasks: pbk_install.yml
  tags:
    - install
- include_vars: vars/{{ ansible_os_family }}.yml
- import_tasks: pbk_config.yml
  tags:
    - config

- import_tasks: pbk_deploy.yml
  tags:
    - deploy
